services:
  - type: web
    name: skipthequeue-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: skipthequeue-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    staticPublishPath: staticfiles
    plan: free
    autoDeploy: true

databases:
  - name: skipthequeue-db
    plan: free 