# Generated by Django 5.2.1 on 2025-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_phone',
            new_name='customer_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='orders.menuitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ready', 'Ready')], default='Pending', max_length=20),
        ),
    ]
