# Generated by Django 5.2.1 on 2025-06-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_user_name_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone',
            new_name='user_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
