# Generated by Django 5.2.1 on 2025-06-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_items_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='orders.menuitem'),
        ),
    ]
