# Generated by Django 5.2 on 2025-06-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_college_menuitem_category_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admin_email',
            field=models.EmailField(default='admin@college.com', max_length=254),
        ),
        migrations.AddField(
            model_name='college',
            name='admin_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='admin_phone',
            field=models.CharField(default='+91-0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='college',
            name='allow_pay_later',
            field=models.BooleanField(default=True, help_text='Allow students to pay later with cash'),
        ),
        migrations.AddField(
            model_name='college',
            name='estimated_preparation_time',
            field=models.IntegerField(default=15, help_text='Default preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='college',
            name='payment_gateway_enabled',
            field=models.BooleanField(default=True, help_text='Enable online payment gateway'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_stock_managed',
            field=models.BooleanField(default=False, help_text='Enable stock management for this item'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online Payment'), ('Cash', 'Pay Later (Cash)')], default='Online', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price when order was placed', max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.college'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_Pending', 'Payment Pending'), ('Paid', 'Paid'), ('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
