# Generated by Django 5.2 on 2025-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_items',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='orders.menuitem'),
        ),
    ]
