# Generated by Django 5.2.1 on 2025-06-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_userprofile_favorite_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('can_accept_orders', models.BooleanField(default=True)),
                ('can_update_status', models.BooleanField(default=True)),
                ('can_view_orders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_staff', to='orders.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'college')},
            },
        ),
    ]
