# Generated by Django 5.2 on 2025-08-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_update_orderitem_model'),
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
    ]
