# Generated by Django 5.2 on 2025-08-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
        # This migration is intentionally empty to handle the case where
        # the updated_at field already exists in the production database
        # The field is already present in the College model, so no action needed
    ]
