# Generated by Django 5.2 on 2025-08-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
