# Generated by Django 5.2 on 2025-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
        # This migration adds the updated_at field to the College model
        # The field already exists in production database, so this will be a no-op there
        migrations.AddField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
