# Generated by Django 5.2 on 2025-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
        # This migration adds the updated_at field to the College model
        # In production, this field already exists, so this migration should be applied with --fake
        # Using RunSQL to handle the case where the column already exists
        migrations.RunSQL(
            # Forward SQL - only add if column doesn't exist
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'orders_college' 
                    AND column_name = 'updated_at'
                ) THEN
                    ALTER TABLE orders_college ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
                END IF;
            END $$;
            """,
            # Reverse SQL - remove the column if it exists
            reverse_sql="""
            ALTER TABLE orders_college DROP COLUMN IF EXISTS updated_at;
            """
        ),
    ]
