# Generated by Django 5.2 on 2025-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_Pending', 'Payment Pending'), ('Paid', 'Paid'), ('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
    ]
