# Generated by Django 5.2 on 2025-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_canteenstaff'),
    ]

    operations = [
        # This migration is designed to be safe for production
        # The updated_at field already exists in production database
        # This migration will be applied with --fake in production
        migrations.AddField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
