# Generated by Django 5.2 on 2025-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_final_updated_at'),
    ]

    operations = [
        # This migration marks the updated_at field as already existing
        # This prevents Django from trying to create it again
        migrations.AddField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
